languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "«Алгебры Ли, алгебраические группы и теория инвариантов»"
baseURL = "https://lie-school.ru/"

# sectionPagesMenu = "main"    


[blackfriday]
  angledQuotes = true
  fractions = false