languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "«Алгебры Ли, алгебраические группы и теория инвариантов»"
baseURL = "http://lie-seminar.netlify.com/"

sectionPagesMenu = "main"    


[blackfriday]
  angledQuotes = true
  fractions = false